# theme = "github_dark_high_contrast"
theme = "github_light"

[editor]
bufferline = "always"
line-number = "relative"
mouse = false
scrolloff = 12
cursorline = true
rulers = [100]
continue-comments = false
auto-completion = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
auto-signature-help = false
display-inlay-hints = false

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
"'" = "'"

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 5000

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
wrap-indicator =""

[keys.normal]
F1 = ":set whitespace.render none"
F2 = ":set whitespace.render all"

A-x = "extend_to_line_bounds"
X = "select_line_above"

"A-j"   = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
"A-k" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"

[keys.select]
A-x = "extend_to_line_bounds"
X = "select_line_above"
A-v = "split_selection_on_newline"

[keys.insert]
F1 = ":set whitespace.render none"
F2 = ":set whitespace.render all"

up       = "no_op"
down     = "no_op"
left     = "no_op"
right    = "no_op"
pageup   = "no_op"
pagedown = "no_op"
home     = "no_op"
end      = "no_op"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
