[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 100
feature_words = true
feature_snippets = true
snippets_first = true
snippets_inline_by_word_tail = false 
feature_unicode_input = false
feature_paths = false
feature_citations = false

[[language]]
name = "lua"
language-servers = ["scls"]
file-types = ["lua"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "zig"
language-servers = ["zls", "scls"]
scope = "source.zig"
file-types = ["zig", "zig.zon"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
language-servers = ["clangd", "scls"]
scope = "source.c"
file-types = ["c", "h"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
language-servers = ["clangd", "scls"]
scope = "source.cpp"
file-types = ["cpp", "hpp", "ino"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "rust"
indent = { tab-width = 4, unit = "    " }

[language.debugger]
name = "lldb-vscode"
transport = "stdio"
command = "lldb-vscode"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}", initCommands = [ "command script import /usr/local/etc/lldb_vscode_rustc_primer.py" ] }

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "python"
language-servers = ["pyright", "ruff", "scls"]
scope = "source.py"
indent = { tab-width = 4, unit = "    " }

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "markdown"
language-servers = ["markdown-oxide", "scls"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "stub"
scope = "text.stub"
file-types = ["txt", "todo", "md", ""]
shebangs = []
roots = []
auto-format = false
language-servers = [ "scls" ]
indent = { tab-width = 4, unit = "    " }

